api:
  token:
    secret: "${SECRET:file:./jwt_key.secret}"

spring:
  application:
    name: RetroGamePlatform
  config:
    import: "optional:file:./db_credentials.yaml"
  jackson:
    default-property-inclusion: NON_EMPTY
  profiles:
    active: dev